[workspace]
resolver = "2"

members = [
	"lpm/common",
	"lpm/core",
	"lpm/db",
	"lpm/ehandle",
	"lpm/main",
	"libs/hash",
	"libs/json",
	"libs/sql-builder",
	"libs/untar",
	"libs/term",
]

[profile.release]
lto = true
