[package]
name = "db"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
min-sqlite3-sys = "1.3"
ehandle = { path = "../ehandle" }
common = { path = "../common" }
sql-builder = { path = "../../libs/sql-builder" }
term = { path = "../../libs/term" }
